- lib/iotagent-lwm2m-client.js
- lib/services/server/updateRegistration.js
- test/unit/client/client-registration-test.js
- test/unit/server/update-registration-test.js
Update register sends new set of supported objects
> ADD Update register register objects

- lib/services/model/Device.js
- lib/services/server/mongodbDeviceRegistry.js
- lib/services/server/registration.js
- test/unit/server/device-registry-mongo-test.js
Add the information about what is the url used to register the client.
> ADD Information about the url used to register the client

- CHANGES_NEXT_RELEASE
- lib/services/server/inMemoryDeviceRegistry.js
- lib/services/server/mongodbDeviceRegistry.js
> Remove old device registration on the new registration

- .travis.yml
- CHANGES_NEXT_RELEASE
- package.json
- test/unit/server/information-reporting-test.js
Add Travis support to the repository.
> ADD Travis YAML file for CI

- CHANGES_NEXT_RELEASE
- config-mongo.js
- config.js
- lib/lwm2m-server.js
- lib/services/server/inMemoryDeviceRegistry.js
- lib/services/server/informationReporting.js
- lib/services/server/mongodbDeviceRegistry.js
- lib/services/server/registration.js
- lib/services/server/updateRegistration.js
> Check lifetime and unregister devices

- CHANGES_NEXT_RELEASE
- lib/lwm2m-server.js
- lib/services/server/inMemoryDeviceRegistry.js
- lib/services/server/mongodbDeviceRegistry.js
> ADD Lifetime unregistration handler

- CHANGES_NEXT_RELEASE
- package.json
Add information in the Package.json to enable global commands.
> ADD Information to the package.json to expose global commands

- README.md
- lib/errors.js
- lib/lwm2m-client.js
- lib/lwm2m-node-lib.js
- lib/lwm2m-server.js
- lib/services/client/execute.js
- lib/services/client/objectRegistry.js
- lib/services/client/read.js
- lib/services/client/write.js
- lib/services/coapRouter.js
- lib/services/coapUtils.js
- lib/services/server/coapUtils.js
- lib/services/server/deviceManagement.js
- lib/services/server/inMemoryDeviceRegistry.js
- lib/services/server/informationReporting.js
- lib/services/server/mongodbDeviceRegistry.js
- lib/services/server/registration.js
- lib/services/server/unregistration.js
- lib/services/server/updateRegistration.js
- lib/services/slidingWindow.js
> FIX Replace all library name in documentation and licences

- CHANGES_NEXT_RELEASE
- README.md
- docs/contribution.md
> ADD Contribution Guidelines

- lib/services/server/deviceManagement.js
objectType || objectId || resourceId for deviceManagement.writeAttributes and deviceManagement.discover can be zero.
> Support digit as argument in deviceManagement methods.

- package.json
Update the version of the COAP Library
> ADD New version of COAP Library

- bin/iotagent-lwm2m-server.js
- lib/services/server/informationReporting.js
Pull request #94 now done from develop branch
> observed resource update now shows the device URI;

- lib/services/coapRouter.js
> Avoid faster libcoap response

- CHANGES_NEXT_RELEASE
- lib/services/server/informationReporting.js
> Issue observeruseproxy

- CHANGES_NEXT_RELEASE
Merging of PR #120 (develop -> master) has indirectly caused issue #106 to close. This PR adds a mention to it in CNR.
> ADD entry to CNR

- README.md
- config-mongo.js
- lib/commonConfig.js
- lib/constants.js
- lib/lwm2m-server.js
- lib/services/model/dbConn.js
- lib/services/server/mongodbDeviceRegistry.js
- test/unit/server/device-registry-mongo-test.js
fix #123 and #124 
grunt test passing
> standardise configuration and add support for advanced mongo configuration

- CHANGES_NEXT_RELEASE
- lib/services/model/dbConn.js
- lib/services/server/mongodbDeviceRegistry.js
- test/unit/server/device-registry-mongo-test.js
This PR removes warnings and deprecations warnings. It is related to https://github.com/telefonicaid/iotagent-node-lib/pull/784
> Fix: removes warnings

- CHANGES_NEXT_RELEASE
- package.json
> Step: 1.1.0-next -> 1.2.0

- .travis.yml
- CHANGES_NEXT_RELEASE
- package.json
Mimics PR https://github.com/telefonicaid/iotagent-json/pull/400
> REMOVE node v6 ADD node v12

- docs/contribution.md
> FIX contributions.md

- README.md
> ADD mongodb requirement to testing procedures

- CHANGES_NEXT_RELEASE
- package.json
Mimics PR https://github.com/telefonicaid/lwm2m-node-lib/pull/144
> Step: 1.2.0-next -> 1.3.0

- CHANGES_NEXT_RELEASE
- package.json
> Step: 1.3.0-next -> 1.4.0

- CHANGES_NEXT_RELEASE
- package.json
Pretty similar to PR https://github.com/telefonicaid/fiware-sth-comet/pull/591
> REMOVE node v8 and v10
